// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FnsParticipants/SearchFnsParticipantsResponse.proto
// Protobuf Java Version: 4.28.3

package Diadoc.Api.Proto.FnsParticipants;

public final class SearchFnsParticipantsResponseOuterClass {
  private SearchFnsParticipantsResponseOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      SearchFnsParticipantsResponseOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus}
   */
  public enum FnsParticipantSearchStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UnknownFnsParticipantSearchStatus = 0;</code>
     */
    UnknownFnsParticipantSearchStatus(0),
    /**
     * <code>OkFnsParticipantSearchStatus = 1;</code>
     */
    OkFnsParticipantSearchStatus(1),
    /**
     * <code>NotFoundFnsParticipantSearchStatus = 2;</code>
     */
    NotFoundFnsParticipantSearchStatus(2),
    /**
     * <code>NotAllowedFnsParticipantSearchStatus = 3;</code>
     */
    NotAllowedFnsParticipantSearchStatus(3),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        FnsParticipantSearchStatus.class.getName());
    }
    /**
     * <code>UnknownFnsParticipantSearchStatus = 0;</code>
     */
    public static final int UnknownFnsParticipantSearchStatus_VALUE = 0;
    /**
     * <code>OkFnsParticipantSearchStatus = 1;</code>
     */
    public static final int OkFnsParticipantSearchStatus_VALUE = 1;
    /**
     * <code>NotFoundFnsParticipantSearchStatus = 2;</code>
     */
    public static final int NotFoundFnsParticipantSearchStatus_VALUE = 2;
    /**
     * <code>NotAllowedFnsParticipantSearchStatus = 3;</code>
     */
    public static final int NotAllowedFnsParticipantSearchStatus_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FnsParticipantSearchStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FnsParticipantSearchStatus forNumber(int value) {
      switch (value) {
        case 0: return UnknownFnsParticipantSearchStatus;
        case 1: return OkFnsParticipantSearchStatus;
        case 2: return NotFoundFnsParticipantSearchStatus;
        case 3: return NotAllowedFnsParticipantSearchStatus;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FnsParticipantSearchStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FnsParticipantSearchStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FnsParticipantSearchStatus>() {
            public FnsParticipantSearchStatus findValueByNumber(int number) {
              return FnsParticipantSearchStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final FnsParticipantSearchStatus[] VALUES = values();

    public static FnsParticipantSearchStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FnsParticipantSearchStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus)
  }

  public interface SearchFnsParticipantsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus Status = 1;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>required .Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus Status = 1;</code>
     * @return The status.
     */
    Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus getStatus();

    /**
     * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
     */
    java.util.List<Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant> 
        getParticipantsList();
    /**
     * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
     */
    Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant getParticipants(int index);
    /**
     * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
     */
    int getParticipantsCount();
    /**
     * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
     */
    java.util.List<? extends Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantOrBuilder> 
        getParticipantsOrBuilderList();
    /**
     * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
     */
    Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantOrBuilder getParticipantsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponse}
   */
  public static final class SearchFnsParticipantsResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponse)
      SearchFnsParticipantsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        SearchFnsParticipantsResponse.class.getName());
    }
    // Use SearchFnsParticipantsResponse.newBuilder() to construct.
    private SearchFnsParticipantsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SearchFnsParticipantsResponse() {
      status_ = 0;
      participants_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.internal_static_Diadoc_Api_Proto_FnsParticipants_SearchFnsParticipantsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.internal_static_Diadoc_Api_Proto_FnsParticipants_SearchFnsParticipantsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse.class, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse.Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_ = 0;
    /**
     * <code>required .Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus Status = 1;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus Status = 1;</code>
     * @return The status.
     */
    @java.lang.Override public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus getStatus() {
      Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus result = Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus.forNumber(status_);
      return result == null ? Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus.UnknownFnsParticipantSearchStatus : result;
    }

    public static final int PARTICIPANTS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant> participants_;
    /**
     * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
     */
    @java.lang.Override
    public java.util.List<Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant> getParticipantsList() {
      return participants_;
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantOrBuilder> 
        getParticipantsOrBuilderList() {
      return participants_;
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
     */
    @java.lang.Override
    public int getParticipantsCount() {
      return participants_.size();
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
     */
    @java.lang.Override
    public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant getParticipants(int index) {
      return participants_.get(index);
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
     */
    @java.lang.Override
    public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantOrBuilder getParticipantsOrBuilder(
        int index) {
      return participants_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getParticipantsCount(); i++) {
        if (!getParticipants(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, status_);
      }
      for (int i = 0; i < participants_.size(); i++) {
        output.writeMessage(2, participants_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      for (int i = 0; i < participants_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, participants_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse)) {
        return super.equals(obj);
      }
      Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse other = (Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse) obj;

      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (status_ != other.status_) return false;
      }
      if (!getParticipantsList()
          .equals(other.getParticipantsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      if (getParticipantsCount() > 0) {
        hash = (37 * hash) + PARTICIPANTS_FIELD_NUMBER;
        hash = (53 * hash) + getParticipantsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponse)
        Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.internal_static_Diadoc_Api_Proto_FnsParticipants_SearchFnsParticipantsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.internal_static_Diadoc_Api_Proto_FnsParticipants_SearchFnsParticipantsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse.class, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        status_ = 0;
        if (participantsBuilder_ == null) {
          participants_ = java.util.Collections.emptyList();
        } else {
          participants_ = null;
          participantsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.internal_static_Diadoc_Api_Proto_FnsParticipants_SearchFnsParticipantsResponse_descriptor;
      }

      @java.lang.Override
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse getDefaultInstanceForType() {
        return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse build() {
        Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse buildPartial() {
        Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse result = new Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse result) {
        if (participantsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            participants_ = java.util.Collections.unmodifiableList(participants_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.participants_ = participants_;
        } else {
          result.participants_ = participantsBuilder_.build();
        }
      }

      private void buildPartial0(Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.status_ = status_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse) {
          return mergeFrom((Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse other) {
        if (other == Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (participantsBuilder_ == null) {
          if (!other.participants_.isEmpty()) {
            if (participants_.isEmpty()) {
              participants_ = other.participants_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureParticipantsIsMutable();
              participants_.addAll(other.participants_);
            }
            onChanged();
          }
        } else {
          if (!other.participants_.isEmpty()) {
            if (participantsBuilder_.isEmpty()) {
              participantsBuilder_.dispose();
              participantsBuilder_ = null;
              participants_ = other.participants_;
              bitField0_ = (bitField0_ & ~0x00000002);
              participantsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParticipantsFieldBuilder() : null;
            } else {
              participantsBuilder_.addAllMessages(other.participants_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStatus()) {
          return false;
        }
        for (int i = 0; i < getParticipantsCount(); i++) {
          if (!getParticipants(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus tmpValue =
                    Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(1, tmpRaw);
                } else {
                  status_ = tmpRaw;
                  bitField0_ |= 0x00000001;
                }
                break;
              } // case 8
              case 18: {
                Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant m =
                    input.readMessage(
                        Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.parser(),
                        extensionRegistry);
                if (participantsBuilder_ == null) {
                  ensureParticipantsIsMutable();
                  participants_.add(m);
                } else {
                  participantsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>required .Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus Status = 1;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus Status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus getStatus() {
        Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus result = Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus.forNumber(status_);
        return result == null ? Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus.UnknownFnsParticipantSearchStatus : result;
      }
      /**
       * <code>required .Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus Status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantSearchStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Diadoc.Api.Proto.FnsParticipants.FnsParticipantSearchStatus Status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant> participants_ =
        java.util.Collections.emptyList();
      private void ensureParticipantsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          participants_ = new java.util.ArrayList<Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant>(participants_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantOrBuilder> participantsBuilder_;

      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public java.util.List<Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant> getParticipantsList() {
        if (participantsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(participants_);
        } else {
          return participantsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public int getParticipantsCount() {
        if (participantsBuilder_ == null) {
          return participants_.size();
        } else {
          return participantsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant getParticipants(int index) {
        if (participantsBuilder_ == null) {
          return participants_.get(index);
        } else {
          return participantsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Builder setParticipants(
          int index, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant value) {
        if (participantsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParticipantsIsMutable();
          participants_.set(index, value);
          onChanged();
        } else {
          participantsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Builder setParticipants(
          int index, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder builderForValue) {
        if (participantsBuilder_ == null) {
          ensureParticipantsIsMutable();
          participants_.set(index, builderForValue.build());
          onChanged();
        } else {
          participantsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Builder addParticipants(Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant value) {
        if (participantsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParticipantsIsMutable();
          participants_.add(value);
          onChanged();
        } else {
          participantsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Builder addParticipants(
          int index, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant value) {
        if (participantsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParticipantsIsMutable();
          participants_.add(index, value);
          onChanged();
        } else {
          participantsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Builder addParticipants(
          Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder builderForValue) {
        if (participantsBuilder_ == null) {
          ensureParticipantsIsMutable();
          participants_.add(builderForValue.build());
          onChanged();
        } else {
          participantsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Builder addParticipants(
          int index, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder builderForValue) {
        if (participantsBuilder_ == null) {
          ensureParticipantsIsMutable();
          participants_.add(index, builderForValue.build());
          onChanged();
        } else {
          participantsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Builder addAllParticipants(
          java.lang.Iterable<? extends Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant> values) {
        if (participantsBuilder_ == null) {
          ensureParticipantsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, participants_);
          onChanged();
        } else {
          participantsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Builder clearParticipants() {
        if (participantsBuilder_ == null) {
          participants_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          participantsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Builder removeParticipants(int index) {
        if (participantsBuilder_ == null) {
          ensureParticipantsIsMutable();
          participants_.remove(index);
          onChanged();
        } else {
          participantsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder getParticipantsBuilder(
          int index) {
        return getParticipantsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantOrBuilder getParticipantsOrBuilder(
          int index) {
        if (participantsBuilder_ == null) {
          return participants_.get(index);  } else {
          return participantsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public java.util.List<? extends Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantOrBuilder> 
           getParticipantsOrBuilderList() {
        if (participantsBuilder_ != null) {
          return participantsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(participants_);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder addParticipantsBuilder() {
        return getParticipantsFieldBuilder().addBuilder(
            Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.getDefaultInstance());
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder addParticipantsBuilder(
          int index) {
        return getParticipantsFieldBuilder().addBuilder(
            index, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.getDefaultInstance());
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.FnsParticipants.FnsParticipant Participants = 2;</code>
       */
      public java.util.List<Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder> 
           getParticipantsBuilderList() {
        return getParticipantsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantOrBuilder> 
          getParticipantsFieldBuilder() {
        if (participantsBuilder_ == null) {
          participantsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantOrBuilder>(
                  participants_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          participants_ = null;
        }
        return participantsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponse)
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponse)
    private static final Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse();
    }

    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchFnsParticipantsResponse>
        PARSER = new com.google.protobuf.AbstractParser<SearchFnsParticipantsResponse>() {
      @java.lang.Override
      public SearchFnsParticipantsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SearchFnsParticipantsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchFnsParticipantsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.SearchFnsParticipantsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FnsParticipantOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.FnsParticipants.FnsParticipant)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string FnsParticipantId = 1;</code>
     * @return Whether the fnsParticipantId field is set.
     */
    boolean hasFnsParticipantId();
    /**
     * <code>required string FnsParticipantId = 1;</code>
     * @return The fnsParticipantId.
     */
    java.lang.String getFnsParticipantId();
    /**
     * <code>required string FnsParticipantId = 1;</code>
     * @return The bytes for fnsParticipantId.
     */
    com.google.protobuf.ByteString
        getFnsParticipantIdBytes();

    /**
     * <code>required string Inn = 2;</code>
     * @return Whether the inn field is set.
     */
    boolean hasInn();
    /**
     * <code>required string Inn = 2;</code>
     * @return The inn.
     */
    java.lang.String getInn();
    /**
     * <code>required string Inn = 2;</code>
     * @return The bytes for inn.
     */
    com.google.protobuf.ByteString
        getInnBytes();

    /**
     * <code>optional string Kpp = 3;</code>
     * @return Whether the kpp field is set.
     */
    boolean hasKpp();
    /**
     * <code>optional string Kpp = 3;</code>
     * @return The kpp.
     */
    java.lang.String getKpp();
    /**
     * <code>optional string Kpp = 3;</code>
     * @return The bytes for kpp.
     */
    com.google.protobuf.ByteString
        getKppBytes();

    /**
     * <code>required string FullName = 4;</code>
     * @return Whether the fullName field is set.
     */
    boolean hasFullName();
    /**
     * <code>required string FullName = 4;</code>
     * @return The fullName.
     */
    java.lang.String getFullName();
    /**
     * <code>required string FullName = 4;</code>
     * @return The bytes for fullName.
     */
    com.google.protobuf.ByteString
        getFullNameBytes();
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.FnsParticipants.FnsParticipant}
   */
  public static final class FnsParticipant extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.FnsParticipants.FnsParticipant)
      FnsParticipantOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        FnsParticipant.class.getName());
    }
    // Use FnsParticipant.newBuilder() to construct.
    private FnsParticipant(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FnsParticipant() {
      fnsParticipantId_ = "";
      inn_ = "";
      kpp_ = "";
      fullName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.internal_static_Diadoc_Api_Proto_FnsParticipants_FnsParticipant_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.internal_static_Diadoc_Api_Proto_FnsParticipants_FnsParticipant_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.class, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder.class);
    }

    private int bitField0_;
    public static final int FNSPARTICIPANTID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fnsParticipantId_ = "";
    /**
     * <code>required string FnsParticipantId = 1;</code>
     * @return Whether the fnsParticipantId field is set.
     */
    @java.lang.Override
    public boolean hasFnsParticipantId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string FnsParticipantId = 1;</code>
     * @return The fnsParticipantId.
     */
    @java.lang.Override
    public java.lang.String getFnsParticipantId() {
      java.lang.Object ref = fnsParticipantId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fnsParticipantId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string FnsParticipantId = 1;</code>
     * @return The bytes for fnsParticipantId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFnsParticipantIdBytes() {
      java.lang.Object ref = fnsParticipantId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fnsParticipantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INN_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object inn_ = "";
    /**
     * <code>required string Inn = 2;</code>
     * @return Whether the inn field is set.
     */
    @java.lang.Override
    public boolean hasInn() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string Inn = 2;</code>
     * @return The inn.
     */
    @java.lang.Override
    public java.lang.String getInn() {
      java.lang.Object ref = inn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          inn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Inn = 2;</code>
     * @return The bytes for inn.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInnBytes() {
      java.lang.Object ref = inn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KPP_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object kpp_ = "";
    /**
     * <code>optional string Kpp = 3;</code>
     * @return Whether the kpp field is set.
     */
    @java.lang.Override
    public boolean hasKpp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string Kpp = 3;</code>
     * @return The kpp.
     */
    @java.lang.Override
    public java.lang.String getKpp() {
      java.lang.Object ref = kpp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          kpp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Kpp = 3;</code>
     * @return The bytes for kpp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKppBytes() {
      java.lang.Object ref = kpp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kpp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FULLNAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fullName_ = "";
    /**
     * <code>required string FullName = 4;</code>
     * @return Whether the fullName field is set.
     */
    @java.lang.Override
    public boolean hasFullName() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string FullName = 4;</code>
     * @return The fullName.
     */
    @java.lang.Override
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fullName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string FullName = 4;</code>
     * @return The bytes for fullName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFnsParticipantId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFullName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, fnsParticipantId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, inn_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, kpp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, fullName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, fnsParticipantId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, inn_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, kpp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, fullName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant)) {
        return super.equals(obj);
      }
      Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant other = (Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant) obj;

      if (hasFnsParticipantId() != other.hasFnsParticipantId()) return false;
      if (hasFnsParticipantId()) {
        if (!getFnsParticipantId()
            .equals(other.getFnsParticipantId())) return false;
      }
      if (hasInn() != other.hasInn()) return false;
      if (hasInn()) {
        if (!getInn()
            .equals(other.getInn())) return false;
      }
      if (hasKpp() != other.hasKpp()) return false;
      if (hasKpp()) {
        if (!getKpp()
            .equals(other.getKpp())) return false;
      }
      if (hasFullName() != other.hasFullName()) return false;
      if (hasFullName()) {
        if (!getFullName()
            .equals(other.getFullName())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFnsParticipantId()) {
        hash = (37 * hash) + FNSPARTICIPANTID_FIELD_NUMBER;
        hash = (53 * hash) + getFnsParticipantId().hashCode();
      }
      if (hasInn()) {
        hash = (37 * hash) + INN_FIELD_NUMBER;
        hash = (53 * hash) + getInn().hashCode();
      }
      if (hasKpp()) {
        hash = (37 * hash) + KPP_FIELD_NUMBER;
        hash = (53 * hash) + getKpp().hashCode();
      }
      if (hasFullName()) {
        hash = (37 * hash) + FULLNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFullName().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.FnsParticipants.FnsParticipant}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.FnsParticipants.FnsParticipant)
        Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipantOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.internal_static_Diadoc_Api_Proto_FnsParticipants_FnsParticipant_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.internal_static_Diadoc_Api_Proto_FnsParticipants_FnsParticipant_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.class, Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fnsParticipantId_ = "";
        inn_ = "";
        kpp_ = "";
        fullName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.internal_static_Diadoc_Api_Proto_FnsParticipants_FnsParticipant_descriptor;
      }

      @java.lang.Override
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant getDefaultInstanceForType() {
        return Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.getDefaultInstance();
      }

      @java.lang.Override
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant build() {
        Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant buildPartial() {
        Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant result = new Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fnsParticipantId_ = fnsParticipantId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.inn_ = inn_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.kpp_ = kpp_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.fullName_ = fullName_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant) {
          return mergeFrom((Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant other) {
        if (other == Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant.getDefaultInstance()) return this;
        if (other.hasFnsParticipantId()) {
          fnsParticipantId_ = other.fnsParticipantId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasInn()) {
          inn_ = other.inn_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasKpp()) {
          kpp_ = other.kpp_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasFullName()) {
          fullName_ = other.fullName_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFnsParticipantId()) {
          return false;
        }
        if (!hasInn()) {
          return false;
        }
        if (!hasFullName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fnsParticipantId_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                inn_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                kpp_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                fullName_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object fnsParticipantId_ = "";
      /**
       * <code>required string FnsParticipantId = 1;</code>
       * @return Whether the fnsParticipantId field is set.
       */
      public boolean hasFnsParticipantId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string FnsParticipantId = 1;</code>
       * @return The fnsParticipantId.
       */
      public java.lang.String getFnsParticipantId() {
        java.lang.Object ref = fnsParticipantId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fnsParticipantId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string FnsParticipantId = 1;</code>
       * @return The bytes for fnsParticipantId.
       */
      public com.google.protobuf.ByteString
          getFnsParticipantIdBytes() {
        java.lang.Object ref = fnsParticipantId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fnsParticipantId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string FnsParticipantId = 1;</code>
       * @param value The fnsParticipantId to set.
       * @return This builder for chaining.
       */
      public Builder setFnsParticipantId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fnsParticipantId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string FnsParticipantId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFnsParticipantId() {
        fnsParticipantId_ = getDefaultInstance().getFnsParticipantId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string FnsParticipantId = 1;</code>
       * @param value The bytes for fnsParticipantId to set.
       * @return This builder for chaining.
       */
      public Builder setFnsParticipantIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        fnsParticipantId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object inn_ = "";
      /**
       * <code>required string Inn = 2;</code>
       * @return Whether the inn field is set.
       */
      public boolean hasInn() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string Inn = 2;</code>
       * @return The inn.
       */
      public java.lang.String getInn() {
        java.lang.Object ref = inn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            inn_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Inn = 2;</code>
       * @return The bytes for inn.
       */
      public com.google.protobuf.ByteString
          getInnBytes() {
        java.lang.Object ref = inn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          inn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Inn = 2;</code>
       * @param value The inn to set.
       * @return This builder for chaining.
       */
      public Builder setInn(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        inn_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string Inn = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInn() {
        inn_ = getDefaultInstance().getInn();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string Inn = 2;</code>
       * @param value The bytes for inn to set.
       * @return This builder for chaining.
       */
      public Builder setInnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        inn_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object kpp_ = "";
      /**
       * <code>optional string Kpp = 3;</code>
       * @return Whether the kpp field is set.
       */
      public boolean hasKpp() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string Kpp = 3;</code>
       * @return The kpp.
       */
      public java.lang.String getKpp() {
        java.lang.Object ref = kpp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            kpp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Kpp = 3;</code>
       * @return The bytes for kpp.
       */
      public com.google.protobuf.ByteString
          getKppBytes() {
        java.lang.Object ref = kpp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kpp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Kpp = 3;</code>
       * @param value The kpp to set.
       * @return This builder for chaining.
       */
      public Builder setKpp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        kpp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Kpp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearKpp() {
        kpp_ = getDefaultInstance().getKpp();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string Kpp = 3;</code>
       * @param value The bytes for kpp to set.
       * @return This builder for chaining.
       */
      public Builder setKppBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        kpp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object fullName_ = "";
      /**
       * <code>required string FullName = 4;</code>
       * @return Whether the fullName field is set.
       */
      public boolean hasFullName() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string FullName = 4;</code>
       * @return The fullName.
       */
      public java.lang.String getFullName() {
        java.lang.Object ref = fullName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fullName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string FullName = 4;</code>
       * @return The bytes for fullName.
       */
      public com.google.protobuf.ByteString
          getFullNameBytes() {
        java.lang.Object ref = fullName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string FullName = 4;</code>
       * @param value The fullName to set.
       * @return This builder for chaining.
       */
      public Builder setFullName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fullName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required string FullName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFullName() {
        fullName_ = getDefaultInstance().getFullName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>required string FullName = 4;</code>
       * @param value The bytes for fullName to set.
       * @return This builder for chaining.
       */
      public Builder setFullNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        fullName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.FnsParticipants.FnsParticipant)
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.FnsParticipants.FnsParticipant)
    private static final Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant();
    }

    public static Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FnsParticipant>
        PARSER = new com.google.protobuf.AbstractParser<FnsParticipant>() {
      @java.lang.Override
      public FnsParticipant parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FnsParticipant> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FnsParticipant> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Diadoc.Api.Proto.FnsParticipants.SearchFnsParticipantsResponseOuterClass.FnsParticipant getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_FnsParticipants_SearchFnsParticipantsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_FnsParticipants_SearchFnsParticipantsResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_FnsParticipants_FnsParticipant_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_FnsParticipants_FnsParticipant_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3FnsParticipants/SearchFnsParticipantsR" +
      "esponse.proto\022 Diadoc.Api.Proto.FnsParti" +
      "cipants\"\265\001\n\035SearchFnsParticipantsRespons" +
      "e\022L\n\006Status\030\001 \002(\0162<.Diadoc.Api.Proto.Fns" +
      "Participants.FnsParticipantSearchStatus\022" +
      "F\n\014Participants\030\002 \003(\01320.Diadoc.Api.Proto" +
      ".FnsParticipants.FnsParticipant\"V\n\016FnsPa" +
      "rticipant\022\030\n\020FnsParticipantId\030\001 \002(\t\022\013\n\003I" +
      "nn\030\002 \002(\t\022\013\n\003Kpp\030\003 \001(\t\022\020\n\010FullName\030\004 \002(\t*" +
      "\267\001\n\032FnsParticipantSearchStatus\022%\n!Unknow" +
      "nFnsParticipantSearchStatus\020\000\022 \n\034OkFnsPa" +
      "rticipantSearchStatus\020\001\022&\n\"NotFoundFnsPa" +
      "rticipantSearchStatus\020\002\022(\n$NotAllowedFns" +
      "ParticipantSearchStatus\020\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Diadoc_Api_Proto_FnsParticipants_SearchFnsParticipantsResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Diadoc_Api_Proto_FnsParticipants_SearchFnsParticipantsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_FnsParticipants_SearchFnsParticipantsResponse_descriptor,
        new java.lang.String[] { "Status", "Participants", });
    internal_static_Diadoc_Api_Proto_FnsParticipants_FnsParticipant_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Diadoc_Api_Proto_FnsParticipants_FnsParticipant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_FnsParticipants_FnsParticipant_descriptor,
        new java.lang.String[] { "FnsParticipantId", "Inn", "Kpp", "FullName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
