// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Events/PowerOfAttorneyToPost.proto
// Protobuf Java Version: 4.28.1

package Diadoc.Api.Proto.Events;

public final class PowerOfAttorneyToPostProtos {
  private PowerOfAttorneyToPostProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      PowerOfAttorneyToPostProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PowerOfAttorneyToPostOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.Events.PowerOfAttorneyToPost)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
     * @return Whether the fullId field is set.
     */
    boolean hasFullId();
    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
     * @return The fullId.
     */
    Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId getFullId();
    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
     */
    Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullIdOrBuilder getFullIdOrBuilder();

    /**
     * <code>required bool UseDefault = 2;</code>
     * @return Whether the useDefault field is set.
     */
    boolean hasUseDefault();
    /**
     * <code>required bool UseDefault = 2;</code>
     * @return The useDefault.
     */
    boolean getUseDefault();

    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
     * @return The content.
     */
    Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent getContent();
    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
     */
    Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder getContentOrBuilder();

    /**
     * <code>optional bool SendAsFile = 4;</code>
     * @return Whether the sendAsFile field is set.
     */
    boolean hasSendAsFile();
    /**
     * <code>optional bool SendAsFile = 4;</code>
     * @return The sendAsFile.
     */
    boolean getSendAsFile();

    /**
     * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
     */
    java.util.List<Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent> 
        getContentsList();
    /**
     * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
     */
    Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent getContents(int index);
    /**
     * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
     */
    int getContentsCount();
    /**
     * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
     */
    java.util.List<? extends Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder> 
        getContentsOrBuilderList();
    /**
     * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
     */
    Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder getContentsOrBuilder(
        int index);

    /**
     * <code>optional bool UseDocumentContent = 6;</code>
     * @return Whether the useDocumentContent field is set.
     */
    boolean hasUseDocumentContent();
    /**
     * <code>optional bool UseDocumentContent = 6;</code>
     * @return The useDocumentContent.
     */
    boolean getUseDocumentContent();
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.Events.PowerOfAttorneyToPost}
   */
  public static final class PowerOfAttorneyToPost extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.Events.PowerOfAttorneyToPost)
      PowerOfAttorneyToPostOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        PowerOfAttorneyToPost.class.getName());
    }
    // Use PowerOfAttorneyToPost.newBuilder() to construct.
    private PowerOfAttorneyToPost(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PowerOfAttorneyToPost() {
      contents_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.internal_static_Diadoc_Api_Proto_Events_PowerOfAttorneyToPost_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.internal_static_Diadoc_Api_Proto_Events_PowerOfAttorneyToPost_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost.class, Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost.Builder.class);
    }

    private int bitField0_;
    public static final int FULLID_FIELD_NUMBER = 1;
    private Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId fullId_;
    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
     * @return Whether the fullId field is set.
     */
    @java.lang.Override
    public boolean hasFullId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
     * @return The fullId.
     */
    @java.lang.Override
    public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId getFullId() {
      return fullId_ == null ? Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId.getDefaultInstance() : fullId_;
    }
    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
     */
    @java.lang.Override
    public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullIdOrBuilder getFullIdOrBuilder() {
      return fullId_ == null ? Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId.getDefaultInstance() : fullId_;
    }

    public static final int USEDEFAULT_FIELD_NUMBER = 2;
    private boolean useDefault_ = false;
    /**
     * <code>required bool UseDefault = 2;</code>
     * @return Whether the useDefault field is set.
     */
    @java.lang.Override
    public boolean hasUseDefault() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bool UseDefault = 2;</code>
     * @return The useDefault.
     */
    @java.lang.Override
    public boolean getUseDefault() {
      return useDefault_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent content_;
    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent getContent() {
      return content_ == null ? Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.getDefaultInstance() : content_;
    }
    /**
     * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
     */
    @java.lang.Override
    public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder getContentOrBuilder() {
      return content_ == null ? Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.getDefaultInstance() : content_;
    }

    public static final int SENDASFILE_FIELD_NUMBER = 4;
    private boolean sendAsFile_ = false;
    /**
     * <code>optional bool SendAsFile = 4;</code>
     * @return Whether the sendAsFile field is set.
     */
    @java.lang.Override
    public boolean hasSendAsFile() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool SendAsFile = 4;</code>
     * @return The sendAsFile.
     */
    @java.lang.Override
    public boolean getSendAsFile() {
      return sendAsFile_;
    }

    public static final int CONTENTS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private java.util.List<Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent> contents_;
    /**
     * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
     */
    @java.lang.Override
    public java.util.List<Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent> getContentsList() {
      return contents_;
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder> 
        getContentsOrBuilderList() {
      return contents_;
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
     */
    @java.lang.Override
    public int getContentsCount() {
      return contents_.size();
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
     */
    @java.lang.Override
    public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent getContents(int index) {
      return contents_.get(index);
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
     */
    @java.lang.Override
    public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder getContentsOrBuilder(
        int index) {
      return contents_.get(index);
    }

    public static final int USEDOCUMENTCONTENT_FIELD_NUMBER = 6;
    private boolean useDocumentContent_ = false;
    /**
     * <code>optional bool UseDocumentContent = 6;</code>
     * @return Whether the useDocumentContent field is set.
     */
    @java.lang.Override
    public boolean hasUseDocumentContent() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bool UseDocumentContent = 6;</code>
     * @return The useDocumentContent.
     */
    @java.lang.Override
    public boolean getUseDocumentContent() {
      return useDocumentContent_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUseDefault()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasFullId()) {
        if (!getFullId().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasContent()) {
        if (!getContent().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getContentsCount(); i++) {
        if (!getContents(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getFullId());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, useDefault_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getContent());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, sendAsFile_);
      }
      for (int i = 0; i < contents_.size(); i++) {
        output.writeMessage(5, contents_.get(i));
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(6, useDocumentContent_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFullId());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, useDefault_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getContent());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, sendAsFile_);
      }
      for (int i = 0; i < contents_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, contents_.get(i));
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, useDocumentContent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost)) {
        return super.equals(obj);
      }
      Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost other = (Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost) obj;

      if (hasFullId() != other.hasFullId()) return false;
      if (hasFullId()) {
        if (!getFullId()
            .equals(other.getFullId())) return false;
      }
      if (hasUseDefault() != other.hasUseDefault()) return false;
      if (hasUseDefault()) {
        if (getUseDefault()
            != other.getUseDefault()) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasSendAsFile() != other.hasSendAsFile()) return false;
      if (hasSendAsFile()) {
        if (getSendAsFile()
            != other.getSendAsFile()) return false;
      }
      if (!getContentsList()
          .equals(other.getContentsList())) return false;
      if (hasUseDocumentContent() != other.hasUseDocumentContent()) return false;
      if (hasUseDocumentContent()) {
        if (getUseDocumentContent()
            != other.getUseDocumentContent()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFullId()) {
        hash = (37 * hash) + FULLID_FIELD_NUMBER;
        hash = (53 * hash) + getFullId().hashCode();
      }
      if (hasUseDefault()) {
        hash = (37 * hash) + USEDEFAULT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getUseDefault());
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasSendAsFile()) {
        hash = (37 * hash) + SENDASFILE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSendAsFile());
      }
      if (getContentsCount() > 0) {
        hash = (37 * hash) + CONTENTS_FIELD_NUMBER;
        hash = (53 * hash) + getContentsList().hashCode();
      }
      if (hasUseDocumentContent()) {
        hash = (37 * hash) + USEDOCUMENTCONTENT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getUseDocumentContent());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.Events.PowerOfAttorneyToPost}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.Events.PowerOfAttorneyToPost)
        Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPostOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.internal_static_Diadoc_Api_Proto_Events_PowerOfAttorneyToPost_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.internal_static_Diadoc_Api_Proto_Events_PowerOfAttorneyToPost_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost.class, Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getFullIdFieldBuilder();
          getContentFieldBuilder();
          getContentsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fullId_ = null;
        if (fullIdBuilder_ != null) {
          fullIdBuilder_.dispose();
          fullIdBuilder_ = null;
        }
        useDefault_ = false;
        content_ = null;
        if (contentBuilder_ != null) {
          contentBuilder_.dispose();
          contentBuilder_ = null;
        }
        sendAsFile_ = false;
        if (contentsBuilder_ == null) {
          contents_ = java.util.Collections.emptyList();
        } else {
          contents_ = null;
          contentsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        useDocumentContent_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.internal_static_Diadoc_Api_Proto_Events_PowerOfAttorneyToPost_descriptor;
      }

      @java.lang.Override
      public Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost getDefaultInstanceForType() {
        return Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost.getDefaultInstance();
      }

      @java.lang.Override
      public Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost build() {
        Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost buildPartial() {
        Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost result = new Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost result) {
        if (contentsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            contents_ = java.util.Collections.unmodifiableList(contents_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.contents_ = contents_;
        } else {
          result.contents_ = contentsBuilder_.build();
        }
      }

      private void buildPartial0(Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fullId_ = fullIdBuilder_ == null
              ? fullId_
              : fullIdBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.useDefault_ = useDefault_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.content_ = contentBuilder_ == null
              ? content_
              : contentBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sendAsFile_ = sendAsFile_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.useDocumentContent_ = useDocumentContent_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost) {
          return mergeFrom((Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost other) {
        if (other == Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost.getDefaultInstance()) return this;
        if (other.hasFullId()) {
          mergeFullId(other.getFullId());
        }
        if (other.hasUseDefault()) {
          setUseDefault(other.getUseDefault());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        if (other.hasSendAsFile()) {
          setSendAsFile(other.getSendAsFile());
        }
        if (contentsBuilder_ == null) {
          if (!other.contents_.isEmpty()) {
            if (contents_.isEmpty()) {
              contents_ = other.contents_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureContentsIsMutable();
              contents_.addAll(other.contents_);
            }
            onChanged();
          }
        } else {
          if (!other.contents_.isEmpty()) {
            if (contentsBuilder_.isEmpty()) {
              contentsBuilder_.dispose();
              contentsBuilder_ = null;
              contents_ = other.contents_;
              bitField0_ = (bitField0_ & ~0x00000010);
              contentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContentsFieldBuilder() : null;
            } else {
              contentsBuilder_.addAllMessages(other.contents_);
            }
          }
        }
        if (other.hasUseDocumentContent()) {
          setUseDocumentContent(other.getUseDocumentContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasUseDefault()) {
          return false;
        }
        if (hasFullId()) {
          if (!getFullId().isInitialized()) {
            return false;
          }
        }
        if (hasContent()) {
          if (!getContent().isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getContentsCount(); i++) {
          if (!getContents(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getFullIdFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                useDefault_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getContentFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                sendAsFile_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent m =
                    input.readMessage(
                        Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.parser(),
                        extensionRegistry);
                if (contentsBuilder_ == null) {
                  ensureContentsIsMutable();
                  contents_.add(m);
                } else {
                  contentsBuilder_.addMessage(m);
                }
                break;
              } // case 42
              case 48: {
                useDocumentContent_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId fullId_;
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId.Builder, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullIdOrBuilder> fullIdBuilder_;
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
       * @return Whether the fullId field is set.
       */
      public boolean hasFullId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
       * @return The fullId.
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId getFullId() {
        if (fullIdBuilder_ == null) {
          return fullId_ == null ? Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId.getDefaultInstance() : fullId_;
        } else {
          return fullIdBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
       */
      public Builder setFullId(Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId value) {
        if (fullIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fullId_ = value;
        } else {
          fullIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
       */
      public Builder setFullId(
          Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId.Builder builderForValue) {
        if (fullIdBuilder_ == null) {
          fullId_ = builderForValue.build();
        } else {
          fullIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
       */
      public Builder mergeFullId(Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId value) {
        if (fullIdBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            fullId_ != null &&
            fullId_ != Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId.getDefaultInstance()) {
            getFullIdBuilder().mergeFrom(value);
          } else {
            fullId_ = value;
          }
        } else {
          fullIdBuilder_.mergeFrom(value);
        }
        if (fullId_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
       */
      public Builder clearFullId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fullId_ = null;
        if (fullIdBuilder_ != null) {
          fullIdBuilder_.dispose();
          fullIdBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId.Builder getFullIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFullIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullIdOrBuilder getFullIdOrBuilder() {
        if (fullIdBuilder_ != null) {
          return fullIdBuilder_.getMessageOrBuilder();
        } else {
          return fullId_ == null ?
              Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId.getDefaultInstance() : fullId_;
        }
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId FullId = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId.Builder, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullIdOrBuilder> 
          getFullIdFieldBuilder() {
        if (fullIdBuilder_ == null) {
          fullIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullId.Builder, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneyFullIdOrBuilder>(
                  getFullId(),
                  getParentForChildren(),
                  isClean());
          fullId_ = null;
        }
        return fullIdBuilder_;
      }

      private boolean useDefault_ ;
      /**
       * <code>required bool UseDefault = 2;</code>
       * @return Whether the useDefault field is set.
       */
      @java.lang.Override
      public boolean hasUseDefault() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required bool UseDefault = 2;</code>
       * @return The useDefault.
       */
      @java.lang.Override
      public boolean getUseDefault() {
        return useDefault_;
      }
      /**
       * <code>required bool UseDefault = 2;</code>
       * @param value The useDefault to set.
       * @return This builder for chaining.
       */
      public Builder setUseDefault(boolean value) {

        useDefault_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required bool UseDefault = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUseDefault() {
        bitField0_ = (bitField0_ & ~0x00000002);
        useDefault_ = false;
        onChanged();
        return this;
      }

      private Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent content_;
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder> contentBuilder_;
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
       * @return The content.
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
       */
      public Builder setContent(Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
        } else {
          contentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
       */
      public Builder setContent(
          Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
       */
      public Builder mergeContent(Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent value) {
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            content_ != null &&
            content_ != Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.getDefaultInstance()) {
            getContentBuilder().mergeFrom(value);
          } else {
            content_ = value;
          }
        } else {
          contentBuilder_.mergeFrom(value);
        }
        if (content_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = null;
        if (contentBuilder_ != null) {
          contentBuilder_.dispose();
          contentBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder getContentBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.getDefaultInstance() : content_;
        }
      }
      /**
       * <code>optional .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Content = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      private boolean sendAsFile_ ;
      /**
       * <code>optional bool SendAsFile = 4;</code>
       * @return Whether the sendAsFile field is set.
       */
      @java.lang.Override
      public boolean hasSendAsFile() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bool SendAsFile = 4;</code>
       * @return The sendAsFile.
       */
      @java.lang.Override
      public boolean getSendAsFile() {
        return sendAsFile_;
      }
      /**
       * <code>optional bool SendAsFile = 4;</code>
       * @param value The sendAsFile to set.
       * @return This builder for chaining.
       */
      public Builder setSendAsFile(boolean value) {

        sendAsFile_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool SendAsFile = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendAsFile() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sendAsFile_ = false;
        onChanged();
        return this;
      }

      private java.util.List<Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent> contents_ =
        java.util.Collections.emptyList();
      private void ensureContentsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          contents_ = new java.util.ArrayList<Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent>(contents_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder> contentsBuilder_;

      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public java.util.List<Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent> getContentsList() {
        if (contentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contents_);
        } else {
          return contentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public int getContentsCount() {
        if (contentsBuilder_ == null) {
          return contents_.size();
        } else {
          return contentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent getContents(int index) {
        if (contentsBuilder_ == null) {
          return contents_.get(index);
        } else {
          return contentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Builder setContents(
          int index, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent value) {
        if (contentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentsIsMutable();
          contents_.set(index, value);
          onChanged();
        } else {
          contentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Builder setContents(
          int index, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder builderForValue) {
        if (contentsBuilder_ == null) {
          ensureContentsIsMutable();
          contents_.set(index, builderForValue.build());
          onChanged();
        } else {
          contentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Builder addContents(Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent value) {
        if (contentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentsIsMutable();
          contents_.add(value);
          onChanged();
        } else {
          contentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Builder addContents(
          int index, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent value) {
        if (contentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentsIsMutable();
          contents_.add(index, value);
          onChanged();
        } else {
          contentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Builder addContents(
          Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder builderForValue) {
        if (contentsBuilder_ == null) {
          ensureContentsIsMutable();
          contents_.add(builderForValue.build());
          onChanged();
        } else {
          contentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Builder addContents(
          int index, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder builderForValue) {
        if (contentsBuilder_ == null) {
          ensureContentsIsMutable();
          contents_.add(index, builderForValue.build());
          onChanged();
        } else {
          contentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Builder addAllContents(
          java.lang.Iterable<? extends Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent> values) {
        if (contentsBuilder_ == null) {
          ensureContentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contents_);
          onChanged();
        } else {
          contentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Builder clearContents() {
        if (contentsBuilder_ == null) {
          contents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          contentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Builder removeContents(int index) {
        if (contentsBuilder_ == null) {
          ensureContentsIsMutable();
          contents_.remove(index);
          onChanged();
        } else {
          contentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder getContentsBuilder(
          int index) {
        return getContentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder getContentsOrBuilder(
          int index) {
        if (contentsBuilder_ == null) {
          return contents_.get(index);  } else {
          return contentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public java.util.List<? extends Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder> 
           getContentsOrBuilderList() {
        if (contentsBuilder_ != null) {
          return contentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contents_);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder addContentsBuilder() {
        return getContentsFieldBuilder().addBuilder(
            Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.getDefaultInstance());
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder addContentsBuilder(
          int index) {
        return getContentsFieldBuilder().addBuilder(
            index, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.getDefaultInstance());
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent Contents = 5;</code>
       */
      public java.util.List<Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder> 
           getContentsBuilderList() {
        return getContentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder> 
          getContentsFieldBuilder() {
        if (contentsBuilder_ == null) {
          contentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContent.Builder, Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.PowerOfAttorneySignedContentOrBuilder>(
                  contents_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          contents_ = null;
        }
        return contentsBuilder_;
      }

      private boolean useDocumentContent_ ;
      /**
       * <code>optional bool UseDocumentContent = 6;</code>
       * @return Whether the useDocumentContent field is set.
       */
      @java.lang.Override
      public boolean hasUseDocumentContent() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bool UseDocumentContent = 6;</code>
       * @return The useDocumentContent.
       */
      @java.lang.Override
      public boolean getUseDocumentContent() {
        return useDocumentContent_;
      }
      /**
       * <code>optional bool UseDocumentContent = 6;</code>
       * @param value The useDocumentContent to set.
       * @return This builder for chaining.
       */
      public Builder setUseDocumentContent(boolean value) {

        useDocumentContent_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool UseDocumentContent = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUseDocumentContent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        useDocumentContent_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.Events.PowerOfAttorneyToPost)
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.Events.PowerOfAttorneyToPost)
    private static final Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost();
    }

    public static Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PowerOfAttorneyToPost>
        PARSER = new com.google.protobuf.AbstractParser<PowerOfAttorneyToPost>() {
      @java.lang.Override
      public PowerOfAttorneyToPost parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PowerOfAttorneyToPost> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PowerOfAttorneyToPost> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Diadoc.Api.Proto.Events.PowerOfAttorneyToPostProtos.PowerOfAttorneyToPost getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_Events_PowerOfAttorneyToPost_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_Events_PowerOfAttorneyToPost_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"Events/PowerOfAttorneyToPost.proto\022\027Di" +
      "adoc.Api.Proto.Events\032&PowersOfAttorney/" +
      "PowerOfAttorney.proto\"\312\002\n\025PowerOfAttorne" +
      "yToPost\022H\n\006FullId\030\001 \001(\01328.Diadoc.Api.Pro" +
      "to.PowersOfAttorney.PowerOfAttorneyFullI" +
      "d\022\022\n\nUseDefault\030\002 \002(\010\022P\n\007Content\030\003 \001(\0132?" +
      ".Diadoc.Api.Proto.PowersOfAttorney.Power" +
      "OfAttorneySignedContent\022\022\n\nSendAsFile\030\004 " +
      "\001(\010\022Q\n\010Contents\030\005 \003(\0132?.Diadoc.Api.Proto" +
      ".PowersOfAttorney.PowerOfAttorneySignedC" +
      "ontent\022\032\n\022UseDocumentContent\030\006 \001(\010B\035B\033Po" +
      "werOfAttorneyToPostProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.getDescriptor(),
        });
    internal_static_Diadoc_Api_Proto_Events_PowerOfAttorneyToPost_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Diadoc_Api_Proto_Events_PowerOfAttorneyToPost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_Events_PowerOfAttorneyToPost_descriptor,
        new java.lang.String[] { "FullId", "UseDefault", "Content", "SendAsFile", "Contents", "UseDocumentContent", });
    descriptor.resolveAllFeaturesImmutable();
    Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
