// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Invoicing/Signer.proto
// Protobuf Java Version: 4.28.1

package Diadoc.Api.Proto.Invoicing;

public final class SignerProtos {
  private SignerProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      SignerProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SignerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.Invoicing.Signer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes SignerCertificate = 1;</code>
     * @return Whether the signerCertificate field is set.
     */
    boolean hasSignerCertificate();
    /**
     * <code>optional bytes SignerCertificate = 1;</code>
     * @return The signerCertificate.
     */
    com.google.protobuf.ByteString getSignerCertificate();

    /**
     * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
     * @return Whether the signerDetails field is set.
     */
    boolean hasSignerDetails();
    /**
     * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
     * @return The signerDetails.
     */
    Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails getSignerDetails();
    /**
     * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
     */
    Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetailsOrBuilder getSignerDetailsOrBuilder();

    /**
     * <code>optional string SignerCertificateThumbprint = 3;</code>
     * @return Whether the signerCertificateThumbprint field is set.
     */
    boolean hasSignerCertificateThumbprint();
    /**
     * <code>optional string SignerCertificateThumbprint = 3;</code>
     * @return The signerCertificateThumbprint.
     */
    java.lang.String getSignerCertificateThumbprint();
    /**
     * <code>optional string SignerCertificateThumbprint = 3;</code>
     * @return The bytes for signerCertificateThumbprint.
     */
    com.google.protobuf.ByteString
        getSignerCertificateThumbprintBytes();
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.Invoicing.Signer}
   */
  public static final class Signer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.Invoicing.Signer)
      SignerOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        Signer.class.getName());
    }
    // Use Signer.newBuilder() to construct.
    private Signer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Signer() {
      signerCertificate_ = com.google.protobuf.ByteString.EMPTY;
      signerCertificateThumbprint_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.Invoicing.SignerProtos.internal_static_Diadoc_Api_Proto_Invoicing_Signer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.Invoicing.SignerProtos.internal_static_Diadoc_Api_Proto_Invoicing_Signer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.Invoicing.SignerProtos.Signer.class, Diadoc.Api.Proto.Invoicing.SignerProtos.Signer.Builder.class);
    }

    private int bitField0_;
    public static final int SIGNERCERTIFICATE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString signerCertificate_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes SignerCertificate = 1;</code>
     * @return Whether the signerCertificate field is set.
     */
    @java.lang.Override
    public boolean hasSignerCertificate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes SignerCertificate = 1;</code>
     * @return The signerCertificate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignerCertificate() {
      return signerCertificate_;
    }

    public static final int SIGNERDETAILS_FIELD_NUMBER = 2;
    private Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails signerDetails_;
    /**
     * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
     * @return Whether the signerDetails field is set.
     */
    @java.lang.Override
    public boolean hasSignerDetails() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
     * @return The signerDetails.
     */
    @java.lang.Override
    public Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails getSignerDetails() {
      return signerDetails_ == null ? Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.getDefaultInstance() : signerDetails_;
    }
    /**
     * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
     */
    @java.lang.Override
    public Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetailsOrBuilder getSignerDetailsOrBuilder() {
      return signerDetails_ == null ? Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.getDefaultInstance() : signerDetails_;
    }

    public static final int SIGNERCERTIFICATETHUMBPRINT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object signerCertificateThumbprint_ = "";
    /**
     * <code>optional string SignerCertificateThumbprint = 3;</code>
     * @return Whether the signerCertificateThumbprint field is set.
     */
    @java.lang.Override
    public boolean hasSignerCertificateThumbprint() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string SignerCertificateThumbprint = 3;</code>
     * @return The signerCertificateThumbprint.
     */
    @java.lang.Override
    public java.lang.String getSignerCertificateThumbprint() {
      java.lang.Object ref = signerCertificateThumbprint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signerCertificateThumbprint_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string SignerCertificateThumbprint = 3;</code>
     * @return The bytes for signerCertificateThumbprint.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSignerCertificateThumbprintBytes() {
      java.lang.Object ref = signerCertificateThumbprint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signerCertificateThumbprint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasSignerDetails()) {
        if (!getSignerDetails().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, signerCertificate_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getSignerDetails());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, signerCertificateThumbprint_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, signerCertificate_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSignerDetails());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, signerCertificateThumbprint_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Diadoc.Api.Proto.Invoicing.SignerProtos.Signer)) {
        return super.equals(obj);
      }
      Diadoc.Api.Proto.Invoicing.SignerProtos.Signer other = (Diadoc.Api.Proto.Invoicing.SignerProtos.Signer) obj;

      if (hasSignerCertificate() != other.hasSignerCertificate()) return false;
      if (hasSignerCertificate()) {
        if (!getSignerCertificate()
            .equals(other.getSignerCertificate())) return false;
      }
      if (hasSignerDetails() != other.hasSignerDetails()) return false;
      if (hasSignerDetails()) {
        if (!getSignerDetails()
            .equals(other.getSignerDetails())) return false;
      }
      if (hasSignerCertificateThumbprint() != other.hasSignerCertificateThumbprint()) return false;
      if (hasSignerCertificateThumbprint()) {
        if (!getSignerCertificateThumbprint()
            .equals(other.getSignerCertificateThumbprint())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSignerCertificate()) {
        hash = (37 * hash) + SIGNERCERTIFICATE_FIELD_NUMBER;
        hash = (53 * hash) + getSignerCertificate().hashCode();
      }
      if (hasSignerDetails()) {
        hash = (37 * hash) + SIGNERDETAILS_FIELD_NUMBER;
        hash = (53 * hash) + getSignerDetails().hashCode();
      }
      if (hasSignerCertificateThumbprint()) {
        hash = (37 * hash) + SIGNERCERTIFICATETHUMBPRINT_FIELD_NUMBER;
        hash = (53 * hash) + getSignerCertificateThumbprint().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Diadoc.Api.Proto.Invoicing.SignerProtos.Signer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.Invoicing.Signer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.Invoicing.Signer)
        Diadoc.Api.Proto.Invoicing.SignerProtos.SignerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.Invoicing.SignerProtos.internal_static_Diadoc_Api_Proto_Invoicing_Signer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.Invoicing.SignerProtos.internal_static_Diadoc_Api_Proto_Invoicing_Signer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.Invoicing.SignerProtos.Signer.class, Diadoc.Api.Proto.Invoicing.SignerProtos.Signer.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.Invoicing.SignerProtos.Signer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getSignerDetailsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        signerCertificate_ = com.google.protobuf.ByteString.EMPTY;
        signerDetails_ = null;
        if (signerDetailsBuilder_ != null) {
          signerDetailsBuilder_.dispose();
          signerDetailsBuilder_ = null;
        }
        signerCertificateThumbprint_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.Invoicing.SignerProtos.internal_static_Diadoc_Api_Proto_Invoicing_Signer_descriptor;
      }

      @java.lang.Override
      public Diadoc.Api.Proto.Invoicing.SignerProtos.Signer getDefaultInstanceForType() {
        return Diadoc.Api.Proto.Invoicing.SignerProtos.Signer.getDefaultInstance();
      }

      @java.lang.Override
      public Diadoc.Api.Proto.Invoicing.SignerProtos.Signer build() {
        Diadoc.Api.Proto.Invoicing.SignerProtos.Signer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Diadoc.Api.Proto.Invoicing.SignerProtos.Signer buildPartial() {
        Diadoc.Api.Proto.Invoicing.SignerProtos.Signer result = new Diadoc.Api.Proto.Invoicing.SignerProtos.Signer(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Diadoc.Api.Proto.Invoicing.SignerProtos.Signer result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.signerCertificate_ = signerCertificate_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.signerDetails_ = signerDetailsBuilder_ == null
              ? signerDetails_
              : signerDetailsBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.signerCertificateThumbprint_ = signerCertificateThumbprint_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.Invoicing.SignerProtos.Signer) {
          return mergeFrom((Diadoc.Api.Proto.Invoicing.SignerProtos.Signer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.Invoicing.SignerProtos.Signer other) {
        if (other == Diadoc.Api.Proto.Invoicing.SignerProtos.Signer.getDefaultInstance()) return this;
        if (other.hasSignerCertificate()) {
          setSignerCertificate(other.getSignerCertificate());
        }
        if (other.hasSignerDetails()) {
          mergeSignerDetails(other.getSignerDetails());
        }
        if (other.hasSignerCertificateThumbprint()) {
          signerCertificateThumbprint_ = other.signerCertificateThumbprint_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasSignerDetails()) {
          if (!getSignerDetails().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                signerCertificate_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getSignerDetailsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                signerCertificateThumbprint_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString signerCertificate_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes SignerCertificate = 1;</code>
       * @return Whether the signerCertificate field is set.
       */
      @java.lang.Override
      public boolean hasSignerCertificate() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes SignerCertificate = 1;</code>
       * @return The signerCertificate.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSignerCertificate() {
        return signerCertificate_;
      }
      /**
       * <code>optional bytes SignerCertificate = 1;</code>
       * @param value The signerCertificate to set.
       * @return This builder for chaining.
       */
      public Builder setSignerCertificate(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        signerCertificate_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes SignerCertificate = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignerCertificate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        signerCertificate_ = getDefaultInstance().getSignerCertificate();
        onChanged();
        return this;
      }

      private Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails signerDetails_;
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails, Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.Builder, Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetailsOrBuilder> signerDetailsBuilder_;
      /**
       * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
       * @return Whether the signerDetails field is set.
       */
      public boolean hasSignerDetails() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
       * @return The signerDetails.
       */
      public Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails getSignerDetails() {
        if (signerDetailsBuilder_ == null) {
          return signerDetails_ == null ? Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.getDefaultInstance() : signerDetails_;
        } else {
          return signerDetailsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
       */
      public Builder setSignerDetails(Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails value) {
        if (signerDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          signerDetails_ = value;
        } else {
          signerDetailsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
       */
      public Builder setSignerDetails(
          Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.Builder builderForValue) {
        if (signerDetailsBuilder_ == null) {
          signerDetails_ = builderForValue.build();
        } else {
          signerDetailsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
       */
      public Builder mergeSignerDetails(Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails value) {
        if (signerDetailsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            signerDetails_ != null &&
            signerDetails_ != Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.getDefaultInstance()) {
            getSignerDetailsBuilder().mergeFrom(value);
          } else {
            signerDetails_ = value;
          }
        } else {
          signerDetailsBuilder_.mergeFrom(value);
        }
        if (signerDetails_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
       */
      public Builder clearSignerDetails() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signerDetails_ = null;
        if (signerDetailsBuilder_ != null) {
          signerDetailsBuilder_.dispose();
          signerDetailsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
       */
      public Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.Builder getSignerDetailsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSignerDetailsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
       */
      public Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetailsOrBuilder getSignerDetailsOrBuilder() {
        if (signerDetailsBuilder_ != null) {
          return signerDetailsBuilder_.getMessageOrBuilder();
        } else {
          return signerDetails_ == null ?
              Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.getDefaultInstance() : signerDetails_;
        }
      }
      /**
       * <code>optional .Diadoc.Api.Proto.Invoicing.SignerDetails SignerDetails = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails, Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.Builder, Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetailsOrBuilder> 
          getSignerDetailsFieldBuilder() {
        if (signerDetailsBuilder_ == null) {
          signerDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails, Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.Builder, Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetailsOrBuilder>(
                  getSignerDetails(),
                  getParentForChildren(),
                  isClean());
          signerDetails_ = null;
        }
        return signerDetailsBuilder_;
      }

      private java.lang.Object signerCertificateThumbprint_ = "";
      /**
       * <code>optional string SignerCertificateThumbprint = 3;</code>
       * @return Whether the signerCertificateThumbprint field is set.
       */
      public boolean hasSignerCertificateThumbprint() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string SignerCertificateThumbprint = 3;</code>
       * @return The signerCertificateThumbprint.
       */
      public java.lang.String getSignerCertificateThumbprint() {
        java.lang.Object ref = signerCertificateThumbprint_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            signerCertificateThumbprint_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string SignerCertificateThumbprint = 3;</code>
       * @return The bytes for signerCertificateThumbprint.
       */
      public com.google.protobuf.ByteString
          getSignerCertificateThumbprintBytes() {
        java.lang.Object ref = signerCertificateThumbprint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signerCertificateThumbprint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string SignerCertificateThumbprint = 3;</code>
       * @param value The signerCertificateThumbprint to set.
       * @return This builder for chaining.
       */
      public Builder setSignerCertificateThumbprint(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        signerCertificateThumbprint_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string SignerCertificateThumbprint = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignerCertificateThumbprint() {
        signerCertificateThumbprint_ = getDefaultInstance().getSignerCertificateThumbprint();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string SignerCertificateThumbprint = 3;</code>
       * @param value The bytes for signerCertificateThumbprint to set.
       * @return This builder for chaining.
       */
      public Builder setSignerCertificateThumbprintBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        signerCertificateThumbprint_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.Invoicing.Signer)
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.Invoicing.Signer)
    private static final Diadoc.Api.Proto.Invoicing.SignerProtos.Signer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Diadoc.Api.Proto.Invoicing.SignerProtos.Signer();
    }

    public static Diadoc.Api.Proto.Invoicing.SignerProtos.Signer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Signer>
        PARSER = new com.google.protobuf.AbstractParser<Signer>() {
      @java.lang.Override
      public Signer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Signer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Signer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Diadoc.Api.Proto.Invoicing.SignerProtos.Signer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignerDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.Invoicing.SignerDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string Surname = 1;</code>
     * @return Whether the surname field is set.
     */
    boolean hasSurname();
    /**
     * <code>required string Surname = 1;</code>
     * @return The surname.
     */
    java.lang.String getSurname();
    /**
     * <code>required string Surname = 1;</code>
     * @return The bytes for surname.
     */
    com.google.protobuf.ByteString
        getSurnameBytes();

    /**
     * <code>required string FirstName = 2;</code>
     * @return Whether the firstName field is set.
     */
    boolean hasFirstName();
    /**
     * <code>required string FirstName = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>required string FirstName = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>optional string Patronymic = 3;</code>
     * @return Whether the patronymic field is set.
     */
    boolean hasPatronymic();
    /**
     * <code>optional string Patronymic = 3;</code>
     * @return The patronymic.
     */
    java.lang.String getPatronymic();
    /**
     * <code>optional string Patronymic = 3;</code>
     * @return The bytes for patronymic.
     */
    com.google.protobuf.ByteString
        getPatronymicBytes();

    /**
     * <code>optional string JobTitle = 4;</code>
     * @return Whether the jobTitle field is set.
     */
    boolean hasJobTitle();
    /**
     * <code>optional string JobTitle = 4;</code>
     * @return The jobTitle.
     */
    java.lang.String getJobTitle();
    /**
     * <code>optional string JobTitle = 4;</code>
     * @return The bytes for jobTitle.
     */
    com.google.protobuf.ByteString
        getJobTitleBytes();

    /**
     * <code>optional string Inn = 5;</code>
     * @return Whether the inn field is set.
     */
    boolean hasInn();
    /**
     * <code>optional string Inn = 5;</code>
     * @return The inn.
     */
    java.lang.String getInn();
    /**
     * <code>optional string Inn = 5;</code>
     * @return The bytes for inn.
     */
    com.google.protobuf.ByteString
        getInnBytes();

    /**
     * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
     * @return Whether the soleProprietorRegistrationCertificate field is set.
     */
    boolean hasSoleProprietorRegistrationCertificate();
    /**
     * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
     * @return The soleProprietorRegistrationCertificate.
     */
    java.lang.String getSoleProprietorRegistrationCertificate();
    /**
     * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
     * @return The bytes for soleProprietorRegistrationCertificate.
     */
    com.google.protobuf.ByteString
        getSoleProprietorRegistrationCertificateBytes();
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.Invoicing.SignerDetails}
   */
  public static final class SignerDetails extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.Invoicing.SignerDetails)
      SignerDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        SignerDetails.class.getName());
    }
    // Use SignerDetails.newBuilder() to construct.
    private SignerDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SignerDetails() {
      surname_ = "";
      firstName_ = "";
      patronymic_ = "";
      jobTitle_ = "";
      inn_ = "";
      soleProprietorRegistrationCertificate_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.Invoicing.SignerProtos.internal_static_Diadoc_Api_Proto_Invoicing_SignerDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.Invoicing.SignerProtos.internal_static_Diadoc_Api_Proto_Invoicing_SignerDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.class, Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.Builder.class);
    }

    private int bitField0_;
    public static final int SURNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object surname_ = "";
    /**
     * <code>required string Surname = 1;</code>
     * @return Whether the surname field is set.
     */
    @java.lang.Override
    public boolean hasSurname() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string Surname = 1;</code>
     * @return The surname.
     */
    @java.lang.Override
    public java.lang.String getSurname() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          surname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Surname = 1;</code>
     * @return The bytes for surname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        surname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object firstName_ = "";
    /**
     * <code>required string FirstName = 2;</code>
     * @return Whether the firstName field is set.
     */
    @java.lang.Override
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string FirstName = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string FirstName = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATRONYMIC_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object patronymic_ = "";
    /**
     * <code>optional string Patronymic = 3;</code>
     * @return Whether the patronymic field is set.
     */
    @java.lang.Override
    public boolean hasPatronymic() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string Patronymic = 3;</code>
     * @return The patronymic.
     */
    @java.lang.Override
    public java.lang.String getPatronymic() {
      java.lang.Object ref = patronymic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          patronymic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Patronymic = 3;</code>
     * @return The bytes for patronymic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPatronymicBytes() {
      java.lang.Object ref = patronymic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patronymic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOBTITLE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object jobTitle_ = "";
    /**
     * <code>optional string JobTitle = 4;</code>
     * @return Whether the jobTitle field is set.
     */
    @java.lang.Override
    public boolean hasJobTitle() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string JobTitle = 4;</code>
     * @return The jobTitle.
     */
    @java.lang.Override
    public java.lang.String getJobTitle() {
      java.lang.Object ref = jobTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jobTitle_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string JobTitle = 4;</code>
     * @return The bytes for jobTitle.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJobTitleBytes() {
      java.lang.Object ref = jobTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INN_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object inn_ = "";
    /**
     * <code>optional string Inn = 5;</code>
     * @return Whether the inn field is set.
     */
    @java.lang.Override
    public boolean hasInn() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string Inn = 5;</code>
     * @return The inn.
     */
    @java.lang.Override
    public java.lang.String getInn() {
      java.lang.Object ref = inn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          inn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Inn = 5;</code>
     * @return The bytes for inn.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInnBytes() {
      java.lang.Object ref = inn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOLEPROPRIETORREGISTRATIONCERTIFICATE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object soleProprietorRegistrationCertificate_ = "";
    /**
     * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
     * @return Whether the soleProprietorRegistrationCertificate field is set.
     */
    @java.lang.Override
    public boolean hasSoleProprietorRegistrationCertificate() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
     * @return The soleProprietorRegistrationCertificate.
     */
    @java.lang.Override
    public java.lang.String getSoleProprietorRegistrationCertificate() {
      java.lang.Object ref = soleProprietorRegistrationCertificate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          soleProprietorRegistrationCertificate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
     * @return The bytes for soleProprietorRegistrationCertificate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSoleProprietorRegistrationCertificateBytes() {
      java.lang.Object ref = soleProprietorRegistrationCertificate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        soleProprietorRegistrationCertificate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSurname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFirstName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, surname_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, firstName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, patronymic_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, jobTitle_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, inn_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, soleProprietorRegistrationCertificate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, surname_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, firstName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, patronymic_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, jobTitle_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, inn_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, soleProprietorRegistrationCertificate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails)) {
        return super.equals(obj);
      }
      Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails other = (Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails) obj;

      if (hasSurname() != other.hasSurname()) return false;
      if (hasSurname()) {
        if (!getSurname()
            .equals(other.getSurname())) return false;
      }
      if (hasFirstName() != other.hasFirstName()) return false;
      if (hasFirstName()) {
        if (!getFirstName()
            .equals(other.getFirstName())) return false;
      }
      if (hasPatronymic() != other.hasPatronymic()) return false;
      if (hasPatronymic()) {
        if (!getPatronymic()
            .equals(other.getPatronymic())) return false;
      }
      if (hasJobTitle() != other.hasJobTitle()) return false;
      if (hasJobTitle()) {
        if (!getJobTitle()
            .equals(other.getJobTitle())) return false;
      }
      if (hasInn() != other.hasInn()) return false;
      if (hasInn()) {
        if (!getInn()
            .equals(other.getInn())) return false;
      }
      if (hasSoleProprietorRegistrationCertificate() != other.hasSoleProprietorRegistrationCertificate()) return false;
      if (hasSoleProprietorRegistrationCertificate()) {
        if (!getSoleProprietorRegistrationCertificate()
            .equals(other.getSoleProprietorRegistrationCertificate())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSurname()) {
        hash = (37 * hash) + SURNAME_FIELD_NUMBER;
        hash = (53 * hash) + getSurname().hashCode();
      }
      if (hasFirstName()) {
        hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstName().hashCode();
      }
      if (hasPatronymic()) {
        hash = (37 * hash) + PATRONYMIC_FIELD_NUMBER;
        hash = (53 * hash) + getPatronymic().hashCode();
      }
      if (hasJobTitle()) {
        hash = (37 * hash) + JOBTITLE_FIELD_NUMBER;
        hash = (53 * hash) + getJobTitle().hashCode();
      }
      if (hasInn()) {
        hash = (37 * hash) + INN_FIELD_NUMBER;
        hash = (53 * hash) + getInn().hashCode();
      }
      if (hasSoleProprietorRegistrationCertificate()) {
        hash = (37 * hash) + SOLEPROPRIETORREGISTRATIONCERTIFICATE_FIELD_NUMBER;
        hash = (53 * hash) + getSoleProprietorRegistrationCertificate().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.Invoicing.SignerDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.Invoicing.SignerDetails)
        Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.Invoicing.SignerProtos.internal_static_Diadoc_Api_Proto_Invoicing_SignerDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.Invoicing.SignerProtos.internal_static_Diadoc_Api_Proto_Invoicing_SignerDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.class, Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        surname_ = "";
        firstName_ = "";
        patronymic_ = "";
        jobTitle_ = "";
        inn_ = "";
        soleProprietorRegistrationCertificate_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.Invoicing.SignerProtos.internal_static_Diadoc_Api_Proto_Invoicing_SignerDetails_descriptor;
      }

      @java.lang.Override
      public Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails getDefaultInstanceForType() {
        return Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.getDefaultInstance();
      }

      @java.lang.Override
      public Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails build() {
        Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails buildPartial() {
        Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails result = new Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.surname_ = surname_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.firstName_ = firstName_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.patronymic_ = patronymic_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.jobTitle_ = jobTitle_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.inn_ = inn_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.soleProprietorRegistrationCertificate_ = soleProprietorRegistrationCertificate_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails) {
          return mergeFrom((Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails other) {
        if (other == Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails.getDefaultInstance()) return this;
        if (other.hasSurname()) {
          surname_ = other.surname_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasFirstName()) {
          firstName_ = other.firstName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasPatronymic()) {
          patronymic_ = other.patronymic_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasJobTitle()) {
          jobTitle_ = other.jobTitle_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasInn()) {
          inn_ = other.inn_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasSoleProprietorRegistrationCertificate()) {
          soleProprietorRegistrationCertificate_ = other.soleProprietorRegistrationCertificate_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSurname()) {
          return false;
        }
        if (!hasFirstName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                surname_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                firstName_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                patronymic_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                jobTitle_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                inn_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                soleProprietorRegistrationCertificate_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object surname_ = "";
      /**
       * <code>required string Surname = 1;</code>
       * @return Whether the surname field is set.
       */
      public boolean hasSurname() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string Surname = 1;</code>
       * @return The surname.
       */
      public java.lang.String getSurname() {
        java.lang.Object ref = surname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            surname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Surname = 1;</code>
       * @return The bytes for surname.
       */
      public com.google.protobuf.ByteString
          getSurnameBytes() {
        java.lang.Object ref = surname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          surname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Surname = 1;</code>
       * @param value The surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        surname_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string Surname = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSurname() {
        surname_ = getDefaultInstance().getSurname();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string Surname = 1;</code>
       * @param value The bytes for surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        surname_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>required string FirstName = 2;</code>
       * @return Whether the firstName field is set.
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string FirstName = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string FirstName = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string FirstName = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        firstName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string FirstName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        firstName_ = getDefaultInstance().getFirstName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string FirstName = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        firstName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object patronymic_ = "";
      /**
       * <code>optional string Patronymic = 3;</code>
       * @return Whether the patronymic field is set.
       */
      public boolean hasPatronymic() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string Patronymic = 3;</code>
       * @return The patronymic.
       */
      public java.lang.String getPatronymic() {
        java.lang.Object ref = patronymic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            patronymic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Patronymic = 3;</code>
       * @return The bytes for patronymic.
       */
      public com.google.protobuf.ByteString
          getPatronymicBytes() {
        java.lang.Object ref = patronymic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patronymic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Patronymic = 3;</code>
       * @param value The patronymic to set.
       * @return This builder for chaining.
       */
      public Builder setPatronymic(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        patronymic_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Patronymic = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPatronymic() {
        patronymic_ = getDefaultInstance().getPatronymic();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string Patronymic = 3;</code>
       * @param value The bytes for patronymic to set.
       * @return This builder for chaining.
       */
      public Builder setPatronymicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        patronymic_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object jobTitle_ = "";
      /**
       * <code>optional string JobTitle = 4;</code>
       * @return Whether the jobTitle field is set.
       */
      public boolean hasJobTitle() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string JobTitle = 4;</code>
       * @return The jobTitle.
       */
      public java.lang.String getJobTitle() {
        java.lang.Object ref = jobTitle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jobTitle_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string JobTitle = 4;</code>
       * @return The bytes for jobTitle.
       */
      public com.google.protobuf.ByteString
          getJobTitleBytes() {
        java.lang.Object ref = jobTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string JobTitle = 4;</code>
       * @param value The jobTitle to set.
       * @return This builder for chaining.
       */
      public Builder setJobTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        jobTitle_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string JobTitle = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobTitle() {
        jobTitle_ = getDefaultInstance().getJobTitle();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string JobTitle = 4;</code>
       * @param value The bytes for jobTitle to set.
       * @return This builder for chaining.
       */
      public Builder setJobTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        jobTitle_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object inn_ = "";
      /**
       * <code>optional string Inn = 5;</code>
       * @return Whether the inn field is set.
       */
      public boolean hasInn() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string Inn = 5;</code>
       * @return The inn.
       */
      public java.lang.String getInn() {
        java.lang.Object ref = inn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            inn_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Inn = 5;</code>
       * @return The bytes for inn.
       */
      public com.google.protobuf.ByteString
          getInnBytes() {
        java.lang.Object ref = inn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          inn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Inn = 5;</code>
       * @param value The inn to set.
       * @return This builder for chaining.
       */
      public Builder setInn(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        inn_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Inn = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInn() {
        inn_ = getDefaultInstance().getInn();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>optional string Inn = 5;</code>
       * @param value The bytes for inn to set.
       * @return This builder for chaining.
       */
      public Builder setInnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        inn_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object soleProprietorRegistrationCertificate_ = "";
      /**
       * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
       * @return Whether the soleProprietorRegistrationCertificate field is set.
       */
      public boolean hasSoleProprietorRegistrationCertificate() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
       * @return The soleProprietorRegistrationCertificate.
       */
      public java.lang.String getSoleProprietorRegistrationCertificate() {
        java.lang.Object ref = soleProprietorRegistrationCertificate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            soleProprietorRegistrationCertificate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
       * @return The bytes for soleProprietorRegistrationCertificate.
       */
      public com.google.protobuf.ByteString
          getSoleProprietorRegistrationCertificateBytes() {
        java.lang.Object ref = soleProprietorRegistrationCertificate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          soleProprietorRegistrationCertificate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
       * @param value The soleProprietorRegistrationCertificate to set.
       * @return This builder for chaining.
       */
      public Builder setSoleProprietorRegistrationCertificate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        soleProprietorRegistrationCertificate_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoleProprietorRegistrationCertificate() {
        soleProprietorRegistrationCertificate_ = getDefaultInstance().getSoleProprietorRegistrationCertificate();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>optional string SoleProprietorRegistrationCertificate = 6;</code>
       * @param value The bytes for soleProprietorRegistrationCertificate to set.
       * @return This builder for chaining.
       */
      public Builder setSoleProprietorRegistrationCertificateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        soleProprietorRegistrationCertificate_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.Invoicing.SignerDetails)
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.Invoicing.SignerDetails)
    private static final Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails();
    }

    public static Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignerDetails>
        PARSER = new com.google.protobuf.AbstractParser<SignerDetails>() {
      @java.lang.Override
      public SignerDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SignerDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignerDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Diadoc.Api.Proto.Invoicing.SignerProtos.SignerDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_Invoicing_Signer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_Invoicing_Signer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_Invoicing_SignerDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_Invoicing_SignerDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026Invoicing/Signer.proto\022\032Diadoc.Api.Pro" +
      "to.Invoicing\"\212\001\n\006Signer\022\031\n\021SignerCertifi" +
      "cate\030\001 \001(\014\022@\n\rSignerDetails\030\002 \001(\0132).Diad" +
      "oc.Api.Proto.Invoicing.SignerDetails\022#\n\033" +
      "SignerCertificateThumbprint\030\003 \001(\t\"\225\001\n\rSi" +
      "gnerDetails\022\017\n\007Surname\030\001 \002(\t\022\021\n\tFirstNam" +
      "e\030\002 \002(\t\022\022\n\nPatronymic\030\003 \001(\t\022\020\n\010JobTitle\030" +
      "\004 \001(\t\022\013\n\003Inn\030\005 \001(\t\022-\n%SoleProprietorRegi" +
      "strationCertificate\030\006 \001(\tB\016B\014SignerProto" +
      "s"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Diadoc_Api_Proto_Invoicing_Signer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Diadoc_Api_Proto_Invoicing_Signer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_Invoicing_Signer_descriptor,
        new java.lang.String[] { "SignerCertificate", "SignerDetails", "SignerCertificateThumbprint", });
    internal_static_Diadoc_Api_Proto_Invoicing_SignerDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Diadoc_Api_Proto_Invoicing_SignerDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_Invoicing_SignerDetails_descriptor,
        new java.lang.String[] { "Surname", "FirstName", "Patronymic", "JobTitle", "Inn", "SoleProprietorRegistrationCertificate", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
