// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OuterDocflows/OuterDocflow.proto

package Diadoc.Api.Proto.OuterDocflows;

public final class OuterDocflowProtos {
  private OuterDocflowProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OuterDocflowInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.OuterDocflows.OuterDocflowInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string DocflowNamedId = 1;</code>
     */
    boolean hasDocflowNamedId();
    /**
     * <code>required string DocflowNamedId = 1;</code>
     */
    java.lang.String getDocflowNamedId();
    /**
     * <code>required string DocflowNamedId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDocflowNamedIdBytes();

    /**
     * <code>required string DocflowFriendlyName = 2;</code>
     */
    boolean hasDocflowFriendlyName();
    /**
     * <code>required string DocflowFriendlyName = 2;</code>
     */
    java.lang.String getDocflowFriendlyName();
    /**
     * <code>required string DocflowFriendlyName = 2;</code>
     */
    com.google.protobuf.ByteString
        getDocflowFriendlyNameBytes();

    /**
     * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
     */
    Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status getStatus();
    /**
     * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
     */
    Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.StatusOrBuilder getStatusOrBuilder();
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.OuterDocflows.OuterDocflowInfo}
   */
  public static final class OuterDocflowInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.OuterDocflows.OuterDocflowInfo)
      OuterDocflowInfoOrBuilder {
    // Use OuterDocflowInfo.newBuilder() to construct.
    private OuterDocflowInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OuterDocflowInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OuterDocflowInfo defaultInstance;
    public static OuterDocflowInfo getDefaultInstance() {
      return defaultInstance;
    }

    public OuterDocflowInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OuterDocflowInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              docflowNamedId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              docflowFriendlyName_ = bs;
              break;
            }
            case 26: {
              Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.internal_static_Diadoc_Api_Proto_OuterDocflows_OuterDocflowInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.internal_static_Diadoc_Api_Proto_OuterDocflows_OuterDocflowInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo.class, Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<OuterDocflowInfo> PARSER =
        new com.google.protobuf.AbstractParser<OuterDocflowInfo>() {
      public OuterDocflowInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OuterDocflowInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OuterDocflowInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DOCFLOWNAMEDID_FIELD_NUMBER = 1;
    private java.lang.Object docflowNamedId_;
    /**
     * <code>required string DocflowNamedId = 1;</code>
     */
    public boolean hasDocflowNamedId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string DocflowNamedId = 1;</code>
     */
    public java.lang.String getDocflowNamedId() {
      java.lang.Object ref = docflowNamedId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          docflowNamedId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string DocflowNamedId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDocflowNamedIdBytes() {
      java.lang.Object ref = docflowNamedId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        docflowNamedId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCFLOWFRIENDLYNAME_FIELD_NUMBER = 2;
    private java.lang.Object docflowFriendlyName_;
    /**
     * <code>required string DocflowFriendlyName = 2;</code>
     */
    public boolean hasDocflowFriendlyName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string DocflowFriendlyName = 2;</code>
     */
    public java.lang.String getDocflowFriendlyName() {
      java.lang.Object ref = docflowFriendlyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          docflowFriendlyName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string DocflowFriendlyName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDocflowFriendlyNameBytes() {
      java.lang.Object ref = docflowFriendlyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        docflowFriendlyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status status_;
    /**
     * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
     */
    public Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status getStatus() {
      return status_;
    }
    /**
     * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
     */
    public Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.StatusOrBuilder getStatusOrBuilder() {
      return status_;
    }

    private void initFields() {
      docflowNamedId_ = "";
      docflowFriendlyName_ = "";
      status_ = Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDocflowNamedId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDocflowFriendlyName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getStatus().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDocflowNamedIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDocflowFriendlyNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDocflowNamedIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDocflowFriendlyNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.OuterDocflows.OuterDocflowInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.OuterDocflows.OuterDocflowInfo)
        Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.internal_static_Diadoc_Api_Proto_OuterDocflows_OuterDocflowInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.internal_static_Diadoc_Api_Proto_OuterDocflows_OuterDocflowInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo.class, Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStatusFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        docflowNamedId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        docflowFriendlyName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (statusBuilder_ == null) {
          status_ = Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.getDefaultInstance();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.internal_static_Diadoc_Api_Proto_OuterDocflows_OuterDocflowInfo_descriptor;
      }

      public Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo getDefaultInstanceForType() {
        return Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo.getDefaultInstance();
      }

      public Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo build() {
        Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo buildPartial() {
        Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo result = new Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.docflowNamedId_ = docflowNamedId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.docflowFriendlyName_ = docflowFriendlyName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo) {
          return mergeFrom((Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo other) {
        if (other == Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo.getDefaultInstance()) return this;
        if (other.hasDocflowNamedId()) {
          bitField0_ |= 0x00000001;
          docflowNamedId_ = other.docflowNamedId_;
          onChanged();
        }
        if (other.hasDocflowFriendlyName()) {
          bitField0_ |= 0x00000002;
          docflowFriendlyName_ = other.docflowFriendlyName_;
          onChanged();
        }
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDocflowNamedId()) {
          
          return false;
        }
        if (!hasDocflowFriendlyName()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!getStatus().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Diadoc.Api.Proto.OuterDocflows.OuterDocflowProtos.OuterDocflowInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object docflowNamedId_ = "";
      /**
       * <code>required string DocflowNamedId = 1;</code>
       */
      public boolean hasDocflowNamedId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string DocflowNamedId = 1;</code>
       */
      public java.lang.String getDocflowNamedId() {
        java.lang.Object ref = docflowNamedId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            docflowNamedId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string DocflowNamedId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDocflowNamedIdBytes() {
        java.lang.Object ref = docflowNamedId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          docflowNamedId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string DocflowNamedId = 1;</code>
       */
      public Builder setDocflowNamedId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        docflowNamedId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string DocflowNamedId = 1;</code>
       */
      public Builder clearDocflowNamedId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        docflowNamedId_ = getDefaultInstance().getDocflowNamedId();
        onChanged();
        return this;
      }
      /**
       * <code>required string DocflowNamedId = 1;</code>
       */
      public Builder setDocflowNamedIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        docflowNamedId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object docflowFriendlyName_ = "";
      /**
       * <code>required string DocflowFriendlyName = 2;</code>
       */
      public boolean hasDocflowFriendlyName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string DocflowFriendlyName = 2;</code>
       */
      public java.lang.String getDocflowFriendlyName() {
        java.lang.Object ref = docflowFriendlyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            docflowFriendlyName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string DocflowFriendlyName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDocflowFriendlyNameBytes() {
        java.lang.Object ref = docflowFriendlyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          docflowFriendlyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string DocflowFriendlyName = 2;</code>
       */
      public Builder setDocflowFriendlyName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        docflowFriendlyName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string DocflowFriendlyName = 2;</code>
       */
      public Builder clearDocflowFriendlyName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        docflowFriendlyName_ = getDefaultInstance().getDocflowFriendlyName();
        onChanged();
        return this;
      }
      /**
       * <code>required string DocflowFriendlyName = 2;</code>
       */
      public Builder setDocflowFriendlyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        docflowFriendlyName_ = value;
        onChanged();
        return this;
      }

      private Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status status_ = Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status, Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.Builder, Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.StatusOrBuilder> statusBuilder_;
      /**
       * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
       */
      public Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status getStatus() {
        if (statusBuilder_ == null) {
          return status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
       */
      public Builder setStatus(Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
       */
      public Builder setStatus(
          Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
       */
      public Builder mergeStatus(Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status value) {
        if (statusBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              status_ != Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.getDefaultInstance()) {
            status_ =
              Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.getDefaultInstance();
          onChanged();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
       */
      public Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.Builder getStatusBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
       */
      public Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.StatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_;
        }
      }
      /**
       * <code>required .Diadoc.Api.Proto.OuterDocflows.Status Status = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status, Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.Builder, Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.StatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status, Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.Status.Builder, Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.StatusOrBuilder>(
                  getStatus(),
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.OuterDocflows.OuterDocflowInfo)
    }

    static {
      defaultInstance = new OuterDocflowInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.OuterDocflows.OuterDocflowInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_OuterDocflows_OuterDocflowInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_OuterDocflows_OuterDocflowInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n OuterDocflows/OuterDocflow.proto\022\036Diad" +
      "oc.Api.Proto.OuterDocflows\032&OuterDocflow" +
      "s/OuterDocflowStatus.proto\"\177\n\020OuterDocfl" +
      "owInfo\022\026\n\016DocflowNamedId\030\001 \002(\t\022\033\n\023Docflo" +
      "wFriendlyName\030\002 \002(\t\0226\n\006Status\030\003 \002(\0132&.Di" +
      "adoc.Api.Proto.OuterDocflows.StatusB\024B\022O" +
      "uterDocflowProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.getDescriptor(),
        }, assigner);
    internal_static_Diadoc_Api_Proto_OuterDocflows_OuterDocflowInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Diadoc_Api_Proto_OuterDocflows_OuterDocflowInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_OuterDocflows_OuterDocflowInfo_descriptor,
        new java.lang.String[] { "DocflowNamedId", "DocflowFriendlyName", "Status", });
    Diadoc.Api.Proto.OuterDocflows.OuterDocflowStatusProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
